### PR TITLE
fix link to blog post

### PR DESCRIPTION
**Pull request by aruediger**

### CODE REVIEW

**Comment by benjamin-actyx** [comment]
:D I think I will have to write another one for this update, too…

**Review by benjamin-actyx — APPROVED** [review]

**Comment by aruediger** [comment]
hehe

**Comment by aruediger** [comment]
could you check the repo settings? i can't merge, request reviews, etc.

**Comment by benjamin-actyx** [comment]
@2beaucoup added you to the actyx-contrib team

**Pull request merged**
